config/routes.rb
Reto3::Application.routes.draw do
  resources :messages
  resource :session
  root :to => "messages#index"
end

app/models/outgoing_message.rb
class OutgoingMessage < ActiveRecord::Base
end

app/models/public_message.rb
class PublicMessage < ActiveRecord::Base
  default_scope order("created_at desc")
  validates_presence_of :from, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :logged_in?, :current_nickname
  
  def logged_in?
    current_nickname.present?
  end
  
  def current_nickname
    session[:nickname]
  end
  
  def require_nickname
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_nickname
  
  def index
    @messages = PublicMessage.limit(100).reverse
  end
  
  def create
    @message = PublicMessage.new(params[:public_message])
    @message.from = current_nickname
    @message.save
    OutgoingMessage.create(@message.attributes)
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.js { @messages = PublicMessage.limit(100).reverse }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    if params[:nickname].present?
      session[:nickname] = params[:nickname]
      redirect_to messages_path
    else
      render "new"
    end
  end
  
  def destroy
    session.delete(:nickname)
    redirect_to new_session_path, :notice => "See you soon!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = 'en'>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Sky Chat" %></title>
    <%= stylesheet_link_tag "application", :media => "all"%>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <% if logged_in? %>
          You are <%= current_nickname %>. <%= link_to "Log out", session_path, :method => :delete %>.
        <% end %>
      </div>

      <div class="center"><h1>Sky Chat</h1></div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_messages.html.erb
<span class="badge badge-info" id="welcome">Welcome to SkyChat Writes your text....</span>
<% @messages.each do |message| %>
  <%= div_for message do %>
    <b><%= message.from %> says:</b> <span class="badge badge-inverse"><%= l message.created_at, :format => "%I:%M%p" %></span><br><span><%= message.content %></span>
  <% end %>
<% end %>
<script type= "text/javascript">
	var count = 1;
	$(".public_message").each(function(){
		if(count%2 == 0){
			$( this ).css("padding-left", "420px");
			$( this ).css("padding-right", "20px");
			$( this ).css("text-align", "right");
		}
		count++;
	});
</script>

app/views/messages/create.js.erb
$("#messages").html(" <%= escape_javascript render("messages") %>");
$("form.new_public_message textarea").val("");

app/views/messages/index.html.erb
<div class="light">
  <%= content_tag :div, :id => "messages", :"data-url" => messages_path(:format => :js) do%>
    <%= render "messages" %>
  <% end %>
  
  <div class="center loading" style="display: none"><%= image_tag "spinner.gif" %></div>
  
  <hr />
  
  <%= form_for PublicMessage.new, :url => messages_path, :remote => true do |f| %>
    <%= f.text_area :content %>
    <div class="controls">
      <button type="submit" class="btn btn-success" type="button">Send</button>
    </div>
  <% end %>
<script type= "text/javascript">
    $('#container').blurjs({
      source: 'body',
      radius: 30
    });
  </script>
</div>

app/views/messages/index.js.erb
$("#messages").html(" <%= escape_javascript render("messages") %>");